### ISSUE TITLE
HTML entities are not parsed

### ISSUE THREAD

**Issue by hawkins** [VendinGoGo/VendinGoGo#12]
HTML entities are not parsed when displaying descriptions. That means our descriptions are left with unparsed entities in them, such as `&#39;` instead of `'`.

Example: `Near the titanic, you&#39;ll find 9 vending machines. Credit card scanners don&#39;t work :(`

**Comment by EliCDavis** [comment]
duplicate of #8

**Comment by hawkins** [comment]
Woops. Comments appear to work as intended tho, in contrast to that issue. Closing here.
