### ISSUE TITLE
Can't Back Out of Gmaps Street View If Invoked

### ISSUE THREAD

**Issue by kalebpace** [VendinGoGo/VendinGoGo#3]
Recreate:
1) drag yellow man to map
2) can't back out due to map styling. Back button is blocked in top left corner of map view.

**Comment by kalebpace** [comment]
I fixed this for desktop, but it still appears for mobile for some reason

**Comment by blond-in-blue** [comment]
Does it still show the little man for you on mobile, Kaleb? It doesn't for me.

**Comment by kalebpace** [comment]
It does not

**Comment by blond-in-blue** [comment]
That's good. Do you think we can mark it as fixed now?
